"""create chat tables

Revision ID: 0591a5f44543
Revises: d2803383d13c
Create Date: 2026-03-25 22:01:07.245592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0591a5f44543'
down_revision: Union[str, None] = 'd2803383d13c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_conversations_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations')),
    sa.UniqueConstraint('id', name=op.f('uq_conversations_id'))
    )
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('retrieved_documents', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('model_used', sa.String(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_messages_conversation_id_conversations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages')),
    sa.UniqueConstraint('id', name=op.f('uq_messages_id'))
    )
    op.create_table('search_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('results_count', sa.Integer(), nullable=False),
    sa.Column('top_result_id', sa.UUID(), nullable=True),
    sa.Column('top_similarity', sa.Float(), nullable=True),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('clicked_result_id', sa.UUID(), nullable=True),
    sa.Column('clicked_position', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clicked_result_id'], ['documents.id'], name=op.f('fk_search_history_clicked_result_id_documents')),
    sa.ForeignKeyConstraint(['top_result_id'], ['documents.id'], name=op.f('fk_search_history_top_result_id_documents')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_search_history_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_search_history')),
    sa.UniqueConstraint('id', name=op.f('uq_search_history_id'))
    )
    op.create_table('user_activities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('activity_type', sa.String(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_user_activities_conversation_id_conversations')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_user_activities_document_id_documents')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_activities_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_activities')),
    sa.UniqueConstraint('id', name=op.f('uq_user_activities_id'))
    )
    op.create_unique_constraint(op.f('uq_categories_id'), 'categories', ['id'])
    op.create_unique_constraint(op.f('uq_documents_id'), 'documents', ['id'])
    op.create_unique_constraint(op.f('uq_roles_id'), 'roles', ['id'])
    op.create_unique_constraint(op.f('uq_users_id'), 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_id'), 'users', type_='unique')
    op.drop_constraint(op.f('uq_roles_id'), 'roles', type_='unique')
    op.drop_constraint(op.f('uq_documents_id'), 'documents', type_='unique')
    op.drop_constraint(op.f('uq_categories_id'), 'categories', type_='unique')
    op.drop_table('user_activities')
    op.drop_table('search_history')
    op.drop_table('messages')
    op.drop_table('conversations')
    # ### end Alembic commands ###
