"""add chat and rag tables

Revision ID: 6e62230bcbee
Revises: e5f6a7b8c9d0
Create Date: 2026-03-04 17:10:22.220710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6e62230bcbee'
down_revision: Union[str, None] = 'e5f6a7b8c9d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop tables with foreign key dependencies first (messages and user_activities depend on conversations)
    op.drop_index('idx_user_activities_activity_type', table_name='user_activities')
    op.drop_index('idx_user_activities_conversation_id', table_name='user_activities', postgresql_where='(conversation_id IS NOT NULL)')
    op.drop_index('idx_user_activities_created_at', table_name='user_activities')
    op.drop_index('idx_user_activities_document_id', table_name='user_activities', postgresql_where='(document_id IS NOT NULL)')
    op.drop_index('idx_user_activities_user_id', table_name='user_activities')
    op.drop_table('user_activities')
    op.drop_index('idx_messages_conversation_id', table_name='messages')
    op.drop_index('idx_messages_created_at', table_name='messages')
    op.drop_index('idx_messages_rating', table_name='messages', postgresql_where='(rating IS NOT NULL)')
    op.drop_index('idx_messages_role', table_name='messages')
    op.drop_table('messages')
    op.drop_index('idx_conversations_created_at', table_name='conversations')
    op.drop_index('idx_conversations_deleted_at', table_name='conversations')
    op.drop_index('idx_conversations_user_id', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index('idx_search_history_created_at', table_name='search_history')
    op.drop_index('idx_search_history_query', table_name='search_history', postgresql_using='gin')
    op.drop_index('idx_search_history_top_result_id', table_name='search_history', postgresql_where='(top_result_id IS NOT NULL)')
    op.drop_index('idx_search_history_user_id', table_name='search_history', postgresql_where='(user_id IS NOT NULL)')
    op.drop_table('search_history')
    op.drop_constraint('categories_title_key', 'categories', type_='unique')
    op.create_unique_constraint(op.f('uq_categories_id'), 'categories', ['id'])
    op.create_unique_constraint(op.f('uq_categories_title'), 'categories', ['title'])
    op.drop_constraint('document_embeddings_document_id_fkey', 'document_embeddings', type_='foreignkey')
    op.create_foreign_key(op.f('fk_document_embeddings_document_id_documents'), 'document_embeddings', 'documents', ['document_id'], ['id'])
    op.create_index('ix_documents_tags', 'documents', ['tags'], unique=False, postgresql_using='gin')
    op.create_unique_constraint(op.f('uq_documents_id'), 'documents', ['id'])
    op.drop_constraint('roles_name_key', 'roles', type_='unique')
    op.create_unique_constraint(op.f('uq_roles_id'), 'roles', ['id'])
    op.create_unique_constraint(op.f('uq_roles_name'), 'roles', ['name'])
    op.drop_index('ix_users_deleted_at', table_name='users')
    op.create_unique_constraint(op.f('uq_users_id'), 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_id'), 'users', type_='unique')
    op.create_index('ix_users_deleted_at', 'users', ['deleted_at'], unique=False)
    op.drop_constraint(op.f('uq_roles_name'), 'roles', type_='unique')
    op.drop_constraint(op.f('uq_roles_id'), 'roles', type_='unique')
    op.create_unique_constraint('roles_name_key', 'roles', ['name'])
    op.drop_constraint(op.f('uq_documents_id'), 'documents', type_='unique')
    op.drop_index('ix_documents_tags', table_name='documents', postgresql_using='gin')
    op.drop_constraint(op.f('fk_document_embeddings_document_id_documents'), 'document_embeddings', type_='foreignkey')
    op.create_foreign_key('document_embeddings_document_id_fkey', 'document_embeddings', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('uq_categories_title'), 'categories', type_='unique')
    op.drop_constraint(op.f('uq_categories_id'), 'categories', type_='unique')
    op.create_unique_constraint('categories_title_key', 'categories', ['title'])
    op.create_table('messages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('conversation_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('retrieved_documents', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('processing_time_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('model_used', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tokens_used', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('feedback', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.CheckConstraint("role::text = ANY (ARRAY['user'::character varying, 'assistant'::character varying]::text[])", name='chk_messages_role'),
    sa.CheckConstraint('rating IS NULL OR rating >= 1 AND rating <= 5', name='chk_messages_rating'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name='fk_messages_conversation', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='messages_pkey')
    )
    op.create_index('idx_messages_role', 'messages', ['role'], unique=False)
    op.create_index('idx_messages_rating', 'messages', ['rating'], unique=False, postgresql_where='(rating IS NOT NULL)')
    op.create_index('idx_messages_created_at', 'messages', ['created_at'], unique=False)
    op.create_index('idx_messages_conversation_id', 'messages', ['conversation_id'], unique=False)
    op.create_table('search_history',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('query', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('results_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('top_result_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('top_similarity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('clicked_result_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('clicked_position', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.CheckConstraint('clicked_position IS NULL OR clicked_position > 0', name='chk_search_history_clicked_position'),
    sa.ForeignKeyConstraint(['clicked_result_id'], ['documents.id'], name='fk_search_history_clicked_result'),
    sa.ForeignKeyConstraint(['top_result_id'], ['documents.id'], name='fk_search_history_top_result'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_search_history_user'),
    sa.PrimaryKeyConstraint('id', name='search_history_pkey')
    )
    op.create_index('idx_search_history_user_id', 'search_history', ['user_id'], unique=False, postgresql_where='(user_id IS NOT NULL)')
    op.create_index('idx_search_history_top_result_id', 'search_history', ['top_result_id'], unique=False, postgresql_where='(top_result_id IS NOT NULL)')
    op.create_index('idx_search_history_query', 'search_history', [sa.text("to_tsvector('english'::regconfig, query)")], unique=False, postgresql_using='gin')
    op.create_index('idx_search_history_created_at', 'search_history', ['created_at'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_conversations_user'),
    sa.PrimaryKeyConstraint('id', name='conversations_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('idx_conversations_user_id', 'conversations', ['user_id'], unique=False)
    op.create_index('idx_conversations_deleted_at', 'conversations', ['deleted_at'], unique=False)
    op.create_index('idx_conversations_created_at', 'conversations', ['created_at'], unique=False)
    op.create_table('user_activities',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('activity_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('document_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('conversation_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name='fk_user_activities_conversation'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name='fk_user_activities_document'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_user_activities_user'),
    sa.PrimaryKeyConstraint('id', name='user_activities_pkey')
    )
    op.create_index('idx_user_activities_user_id', 'user_activities', ['user_id'], unique=False)
    op.create_index('idx_user_activities_document_id', 'user_activities', ['document_id'], unique=False, postgresql_where='(document_id IS NOT NULL)')
    op.create_index('idx_user_activities_created_at', 'user_activities', ['created_at'], unique=False)
    op.create_index('idx_user_activities_conversation_id', 'user_activities', ['conversation_id'], unique=False, postgresql_where='(conversation_id IS NOT NULL)')
    op.create_index('idx_user_activities_activity_type', 'user_activities', ['activity_type'], unique=False)
    # ### end Alembic commands ###
