"""empty message

Revision ID: d911513ed61e
Revises: c1b95eda90d4
Create Date: 2026-02-26 22:29:28.888036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd911513ed61e'
down_revision: Union[str, None] = 'c1b95eda90d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_categories_id'), 'categories', ['id'])
    op.add_column('documents', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_unique_constraint(op.f('uq_documents_id'), 'documents', ['id'])
    op.create_unique_constraint(op.f('uq_roles_id'), 'roles', ['id'])
    op.create_unique_constraint(op.f('uq_users_id'), 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_id'), 'users', type_='unique')
    op.drop_constraint(op.f('uq_roles_id'), 'roles', type_='unique')
    op.drop_constraint(op.f('uq_documents_id'), 'documents', type_='unique')
    op.drop_column('documents', 'metadata')
    op.drop_constraint(op.f('uq_categories_id'), 'categories', type_='unique')
    # ### end Alembic commands ###
