-- ============================================================
-- Legal Assistant - Generate Embeddings for Existing Documents
-- ============================================================
-- This script is a placeholder for embedding generation
-- Embeddings are generated automatically by the Python backend
-- when documents are created or updated
-- ============================================================

\c legal_assist;

-- ============================================================
-- Check Documents Without Embeddings
-- ============================================================

\echo '=== Documents Without Embeddings ==='
SELECT 
    d.id,
    d.title,
    CASE 
        WHEN de.document_id IS NULL THEN 'Missing'
        ELSE 'Present'
    END as embedding_status
FROM documents d
LEFT JOIN document_embeddings de ON d.id = de.document_id
WHERE d.deleted_at IS NULL
ORDER BY d.created_at DESC;

-- ============================================================
-- Embedding Statistics
-- ============================================================

\echo ''
\echo '=== Embedding Statistics ==='
SELECT 
    COUNT(DISTINCT d.id) as total_documents,
    COUNT(DISTINCT de.document_id) as documents_with_embeddings,
    COUNT(DISTINCT d.id) - COUNT(DISTINCT de.document_id) as missing_embeddings
FROM documents d
LEFT JOIN document_embeddings de ON d.id = de.document_id
WHERE d.deleted_at IS NULL;

-- ============================================================
-- Instructions
-- ============================================================

\echo ''
\echo '=== How to Generate Embeddings ==='
\echo ''
\echo 'Embeddings are automatically generated by the backend when:'
\echo '1. A new document is created via POST /documents/'
\echo '2. A document is updated via PUT /documents/{id}'
\echo ''
\echo 'To manually generate embeddings for existing documents:'
\echo '1. cd Backend'
\echo '2. python app/scripts/generate_embeddings_batch.py'
\echo ''
\echo 'Or use the API endpoint:'
\echo 'POST http://localhost:8000/embeddings/generate-batch'
\echo ''
\echo 'To verify embeddings:'
\echo 'GET http://localhost:8000/embeddings/health'
